name: 💥 Report a crash
description: >
  Report a compiler crash or other unexpected program termination caused by an
  exception.
labels: [bug, crash, triage needed]
body:
  - type: markdown
    attributes:
      value: >
        This repository hosts the NeXTCode compiler.
        instead.
  - type: textarea
    attributes:
      label: Description
      description: >
        A concise description of what causes the problem, in human language.
        Though not required, it may help us to more accurately triage the issue
        as well as understand a non-trivial test case.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Reproduction
      description: >
        Provide a test case, preferably in a Markdown codeblock, and explain
        how to build or run it to reproduce the problem. Consider reducing the
        test case to the smallest amount of code possible — a smaller test case
        is easier to reason about and more appealing to contributors.
      value: |
        ```code

        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Stack dump
      description: >
        Paste the stack dump as is, without formatting it into a Markdown
        codeblock.
      render: "text"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: >
        Describe the behavior you expected instead of the crash.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: >
        Provide the Code version, tag, or revision. If you suspect that the
        problem might be specific to a particular development platform or
        deployment target, please specify them as well.
      placeholder: $ codec -version
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: >
        Any complementary information that could help others to work around
        the problem, and us to better understand the problem and its impact.
        For example, a link to a discussion or post that motivated this
        report.
    validations:
      required: false
