name: ⚙️ Track a task
description: >
  Tasks can be used to track internal work, extract individual subtasks from a
  larger issue, and can serve as umbrella issues themselves.
labels: [task, triage needed]
body:
  - type: markdown
    attributes:
      value: >
        This repository hosts the Code compiler, the Code standard library,
        the Code runtime, Source, and IDE support for the Code language.
        It does *not* track feedback on NeXTDeveloper and other closed source NeXTech
        developer software such as Runtime; please direct it to feedback
        instead.
  - type: textarea
    attributes:
      label: Description
      description: >
        A comprehensive description of the task, in human language.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: >
        Any complementary information that could be valuable to an implementor.
    validations:
      required: false
